### ISSUE TITLE
great! gave little tweak

### ISSUE THREAD

**Issue by ghost** [AlexanderWillner/deepl-alfred-workflow2#1]
Thank you, this works perfectly :)
It kept giving me translations into German only - but I fixed this by deleting the other languages and just leaving the ones I want (EN & ES). I rely on this workflow a lot, so happy you found a fix!

**Comment by RyuX51** [comment]
It does only translates into German for me, too. The Readme says:
> To activate this workflow use the default keyword `dl`, enter the passage you wanna get translated and end the input with `.`. Source and destination language will be inferred automatically.

I'm trying to figure out if there's a way to pass a parameter to the workflow to get translations into other languages, too?

**Comment by AlexanderWillner** [comment]
Two options that could be implemented:

1. setting the preferred destination language in the workflow. 

2. passing the target language, for example "dl today will be nice weather > fr" or for more than one target language "dl will it rain today? > fr de". 

What do you think?

**Comment by dotiful** [comment]
It would be useful to be able to change languages using [variables](https://www.alfredapp.com/help/workflows/advanced/variables/), and it's pretty simple to implement

**Comment by RyuX51** [comment]
@AlexanderWillner I like both ideas, this would also be consistent with m9dfukc's workflow. Personally I prefer to set the preferred destination language in the workflow. This allows me to create the workflows `dlde`, `defr` for my most commons translations. Passing the target language is also great though since it doesn't require to copy and modify the workflow for fast translations.

**Comment by AlexanderWillner** [comment]
Implemented it via [environment variable](https://www.alfredapp.com/help/workflows/advanced/variables/). Please test.

**Comment by AlexanderWillner** [comment]
![deepl-setup2](https://user-images.githubusercontent.com/307605/57672674-55f6ac00-7619-11e9-9c0a-ad60762c5de0.png)

**Comment by RyuX51** [comment]
I'm not so sure about the advantage of using the environment variable. In m9dfukc's workflow I could just copy the Script Filter, set the keyword to `dlfr` and modify the script to use `$default_language = 'FR';`. With the environment variable, I set the language for the whole workflow again, so I don't see the advantage here? I always have to open the workflow and change the variable there if I want to get translations for another language? Or do I miss something obvious?

<img width="779" alt="Screenshot 2019-05-14 at 11 43 44" src="https://user-images.githubusercontent.com/1900479/57688372-90724000-763d-11e9-88dd-d4e6db32078c.png">

**Comment by RyuX51** [comment]
However, I solved it now like this:

<img width="597" alt="Screenshot 2019-05-14 at 11 52 09" src="https://user-images.githubusercontent.com/1900479/57688860-b9470500-763e-11e9-8283-023e129697d2.png">

I'm sure the environment variable will be of some use since user @dotiful requested it that way. Thank you for taking the time.

**Comment by AlexanderWillner** [comment]
Good idea. Will provide this option as well.
